In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

In [4]:
item = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기','선풍기', '믹서', '믹서']

In [5]:
encoder = LabelEncoder()
encoder.fit(item)
label = encoder.transform(item) #데이터를 숫자로 바꿈
label

array([0, 1, 4, 5, 3, 3, 2, 2])

In [6]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [7]:
encoder.inverse_transform(label)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
item = [['TV'], ['냉장고'], ['전자레인지'], ['컴퓨터'], ['선풍기'],['선풍기'], ['믹서'], ['믹서']]
#item = np.array(item).reshape(-1,1) #reshape -1은 데이터 갯수만큼, 1은 1개씩 묶어서

In [18]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(item)
oh_label = oh_encoder.transform(item)
oh_label.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [20]:
df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기','선풍기', '믹서', '믹서']})

In [21]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [22]:
# 숫자의 크기가 모델에 영향을 준다 > 원핫 인코딩, 영향 안준다 > 레이블 인코딩


from sklearn.datasets import load_iris
import pandas as pd

In [24]:
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)

In [25]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [26]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
scaler = StandardScaler()
iris_scaled = scaler.fit_transform(iris_df)

In [31]:
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)

In [32]:
iris_df_scaled.mean()

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

In [33]:
iris_df_scaled.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [34]:
iris_df.min()

sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64

In [35]:
iris_df.max()

sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64

In [36]:
from sklearn.preprocessing import MinMaxScaler

In [38]:
scaler = MinMaxScaler()
iris_scaled = scaler.fit_transform(iris_df)
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)

In [39]:
iris_df_scaled.min()

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

In [40]:
iris_df_scaled.max()

sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

In [41]:
train_array = np.arange(0,11).reshape(-1,1)
train_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [42]:
test_array = np.arange(0,6).reshape(-1,1)
test_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [46]:
scaler = MinMaxScaler()
train_scaled = scaler.fit_transform(train_array)

In [47]:
train_scaled

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [49]:
scaler.transform(test_array)
# fit_transform을 사용하면 test_array로 재학습하여 기존 학습이 무의미가 된다

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5]])